### ISSUE TITLE
no simulation parameter values for some models in landingpage

### ISSUE THREAD

**Issue by schuelet** [RakipInitiative/ModelRepository#259]
No actual parameter values are displayed in the simulation view on the landing page  for at least these models.

- secondary model listeria model for µmax of Listeria monocytogenes growing in chilled seafood and meat products model
- Primary model for Listeria monocytogenes growth in constant temperature conditions in chilled seafood and meat products model

**Comment by ganasp** [comment]
I had a look into the metadata regarding the parameters and predefined simulation settings for the two mentioned models (**primary model and secondary model for Listeria**).
For the **primary model** the following parameters with their values are defined:
**default simulation**
N0 <- 1, DA_wph <- 0.0, Storage_period <- 90, Phe <- 0.0, BA_wph <- 0.0, CO2equilibrium <- 0.0, Temp <- 4.0, LA_wph <- 0.0, NIT <- 0.0, pH <- 6.2, NaCl <- 4.0, CA_wph <- 0.0, AA_wph <- 0.0, SA_wph <- 0.0.
For the **secondary model** the following parameters with their values are defined:
**default simulation**
P <- 0, CO2equilibrium <- 0.0, Temp <- 10, LA_wph <- 10, DA_wph <- 10, NIT <- 0, pH <- 6.0, NaCl <- 0.6, CA_wph <- 10, AA_wph <- 10, SA_wph <- 10, BA_wph <- 10
**ham simulation**
P <- 0, CO2equilibrium <- 0.0, Temp <- 10, LA_wph <- 10, DA_wph <- 10, NIT <- 0, pH <- 5.1, NaCl <- 0.6, CA_wph <- 10, AA_wph <- 10, SA_wph <- 10, BA_wph <- 10.
Regarding the question, why these parameters are not displayed with their corresponding values in the simulation view, I can only say, that for these models and their simulation settings the **minimum values** for the parameters are displayed in the simulation view instead of the values for the parameters. All parameters have predefined values, minValues and maxValues and this information is given as metadata of the models.

**Comment by schuelet** [comment]
this has been fixed. Testing required.

**Comment by ganasp** [comment]
What means "Testing required"?
At the moment the situation for the primary model and secondary model for Listeria on the landingpage is still the same, the minimum values are displayed in the simulation view instead of the values for the parameters.

**Comment by schuelet** [comment]
The landingpage is not yet updated, sorry for that. 
Testing of the simulation configurator is still required but I better put that into another ticket.

**Comment by mfilter** [comment]
@schuelet: provide a link to  the "other ticket" and update the landing page, so that @ganasp can test and this ticket can be closed.

**Comment by schuelet** [comment]
landingpage update request has been given to @llavall

**Comment by ganasp** [comment]
Testing LandingPage: Now the correct parameter values are displayed in the simulation view. Parameter values can be adjusted for new simulation setting with a desired number of decimal places.

**Comment by schuelet** [comment]
very good. I am closing this ticket then.
